### ISSUE TITLE
binding_affinity_prediction import error

### ISSUE THREAD

**Issue by JoshuaMeyers** [awslabs/dgl-lifesci#107]
Hey Guys, nice library. I've been trying to run the binding_affinity_prediction example. I built the GPU docker image and installed dgl and dgllifesci. But am unable to run `python main.py --help`. Any ideas? Cheers in advance.

```
(pytorch-ci) root@dgllifesci:/dgllife/dgl-lifesci/examples/binding_affinity_prediction# python main.py --help
DGL backend not selected or invalid.  Assuming PyTorch for now.
Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)
Using backend: pytorch
RDKit is not installed, which is required for utils related to cheminformatics
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from dgllife.utils.eval import Meter
  File "/opt/conda/envs/pytorch-ci/lib/python3.6/site-packages/dgllife/utils/__init__.py", line 6, in <module>
    from .analysis import *
  File "/opt/conda/envs/pytorch-ci/lib/python3.6/site-packages/dgllife/utils/analysis.py", line 14, in <module>
    from rdkit import Chem
  File "/opt/conda/envs/pytorch-ci/lib/python3.6/site-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import DataStructs
  File "/opt/conda/envs/pytorch-ci/lib/python3.6/site-packages/rdkit/DataStructs/__init__.py", line 13, in <module>
    from rdkit.DataStructs import cDataStructs
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /opt/conda/envs/pytorch-ci/lib/python3.6/site-packages/rdkit/DataStructs/../../../../libRDKitDataStructs.so.1)

(pytorch-ci) root@dgllifesci:/dgllife/dgl-lifesci/examples/binding_affinity_prediction# python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit.DataStructs import cDataStructs
[works fine]
```

Given that the latter import works okay, it seems like an environment issue. The setup is done in the `Dockerfile` and I assumed that `pytorch-ci` was the conda env to install into?

**Comment by mufeili** [comment]
These issues seem to be similar to yours:

- https://discuss.pytorch.org/t/import-pytorch-failed/23199
- https://github.com/pytorch/pytorch/issues/8318
- https://www.programmersought.com/article/41851413652/

You may try some solutions suggested there.

**Comment by JoshuaMeyers** [comment]
Thanks for the pointer. [This](https://github.com/pytorch/pytorch/issues/8318#issuecomment-396104261) helped.

If this issue is recurring, might be worth adding 
```
ENV LD_LIBRARY_PATH=/opt/conda/envs/pytorch-ci/lib:${LD_LIBRARY_PATH}
```
To the `Dockerfile`

**Comment by mufeili** [comment]
Glad to know that. Thank you for the update.

**Comment by smilenaderi** [comment]
Hi could you please share your dockerfile?
I built a docker image and cuda is available inside docker container
however inference takes log time
