### ISSUE TITLE
dataset can not load 

### ISSUE THREAD

**Issue by yqdzh** [awslabs/dgl-lifesci#217]
hi here :
 i try to laod the dataset at goolgcolab with this code :
 dataset = PDBBind(subset='refined', pdb_version='v2015', construct_graph_and_featurize=ACNN_graph_construction_and_featurization)but I encounter an error: 
 RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.10/dist-packages/dgllife/utils/complex_to_graph.py", line 272, in ACNN_graph_construction_and_featurization
    ligand_srcs, ligand_dsts, ligand_dists = k_nearest_neighbors(
  File "/usr/local/lib/python3.10/dist-packages/dgllife/utils/mol_to_graph.py", line 702, in k_nearest_neighbors
    dists_i.remove(0)
ValueError: list.remove(x): x not in list
"""
 When I use the core dataset, I do not encounter this error. What could be the reason for this and how can I solve it? Thank  u  !!!

**Comment by mufeili** [comment]
Did you try it in a terminal rather than google colab?

**Comment by yqdzh** [comment]
thanks very much ,i done at terminal

**Comment by mufeili** [comment]
Glad to know that!
